### ISSUE TITLE
Restart error on add-on update

### ISSUE THREAD

**Issue by robertcv** [biolab/orange-canvas-core#186]
I am getting a log of an error in the command prompt. It appears after pressing the OK button to restart Orange for updating/installing add-ones via GUI. Although Orange restarts normally, someone should still look into it so it doesn't cause problems in the future. 

The error:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "/home/robert/git/.../venv/lib/python3.8/site-packages/orangecanvas/application/outputview.py", line 283, in write
    raise ValueError("write operation on a closed stream.")
ValueError: write operation on a closed stream.
Call stack:
  File "/home/robert/git/.../venv/bin/orange-canvas", line 8, in <module>
    sys.exit(main())
  File "/home/robert/git/.../venv/lib/python3.8/site-packages/Orange/canvas/__main__.py", line 706, in main
    log.info('Restarting via exit code 96.')
Message: 'Restarting via exit code 96.'
Arguments: ()
```

- Operating system: Ubuntu 20.04
- Orange canvas version: 0.1.19
- Orange version: 3.28.0
- How you installed Orange: pip

**Comment by markotoplak** [comment]
Thanks, @robertcv. We noticed that these restarts also cause some further errors. They seem connected with what you observe.
