### ISSUE TITLE
Bug in matchDashPattern

### ISSUE THREAD

**Issue by woutdenolf** [biolab/orange-canvas-core#234]
I noticed `matchDashPattern` fails for a certain number of dashes (e.g. 10, 11, 14, ...)

```python
from orangecanvas.canvas.items.nodeitem import drawDashPattern, matchDashPattern

dash6 = drawDashPattern(6)
dash10 = drawDashPattern(10)

matchDashPattern(dash6, dash10)
```

```bash
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    matchDashPattern(dash6, dash10)
  File "/home/denolf/dev/orange-canvas-core/orangecanvas/canvas/items/nodeitem.py", line 585, in matchDashPattern
    new_l1, new_l2 = matchDashPattern(l1s, l2s)
  File "/home/denolf/dev/orange-canvas-core/orangecanvas/canvas/items/nodeitem.py", line 585, in matchDashPattern
    new_l1, new_l2 = matchDashPattern(l1s, l2s)
  File "/home/denolf/dev/orange-canvas-core/orangecanvas/canvas/items/nodeitem.py", line 538, in matchDashPattern
    l1l = l1[l1d]
IndexError: list index out of range
```

Here is a widget with 10 inputs that has the issue:

```python
from orangewidget.widget import OWBaseWidget, Input

class Adder(OWBaseWidget):
    name = "Add two integers"
    description = "Add two numbers"
    icon = "icons/add.svg"

    class Inputs:
        a1 = Input("A1", object)
        a2 = Input("A2", object)
        a3 = Input("A3", object)
        a4 = Input("A4", object)
        a5 = Input("A5", object)
        a6 = Input("A6", object)
        a7 = Input("A7", object)
        a8 = Input("A8", object)
        a9 = Input("A9", object)
        a10 = Input("A10", object)

    @Inputs.a1
    def set_A1(self, a):
        pass

    @Inputs.a2
    def set_A2(self, a):
        pass

    @Inputs.a3
    def set_A3(self, a):
        pass

    @Inputs.a4
    def set_A4(self, a):
        pass

    @Inputs.a5
    def set_A5(self, a):
        pass

    @Inputs.a6
    def set_A6(self, a):
        pass

    @Inputs.a7
    def set_A7(self, a):
        pass

    @Inputs.a8
    def set_A8(self, a):
        pass

    @Inputs.a9
    def set_A9(self, a):
        pass

    @Inputs.a10
    def set_A10(self, a):
        pass
```

**Comment by janezd** [comment]
Thanks for this report. You're right, this code assumes that the number of inputs is rather small (initially, it assumed at most 4!). Is there any chance you could write a patch that handles the remaining cases in some general, though perhaps suboptimal way?

**Comment by woutdenolf** [comment]
> Is there any chance you could write a patch that handles the remaining cases in some general, though perhaps suboptimal way?

Sure. Can you describe what `drawDashPattern` and `drawDashPattern` actually do?

**Comment by janezd** [comment]
No. :) (I have a vague idea.)

@irgolic? @thocevar?
