### ISSUE TITLE
Orange crashes when trying to close it during freeze: 

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-canvas-core#237]
I am unsure whether this was already fixed, but I got the below crash on the latest bundle (3.32.0). It happened when Orange warned me that some add-ons are missing (when opening a saved workflow) and I opted for installing the missing add-ons. Orange froze and when I was trying to close it, the crash appeared.

`Stack Trace:
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/mainwindow.py", line 230, in closeEvent
    super().closeEvent(event)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/application/canvasmain.py", line 2252, in closeEvent
    document.usageStatistics().close()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/document/usagestatistics.py", line 441, in close
    UsageStatistics.statistics_sessions.remove(self)
ValueError: list.remove(x): x not in list`

**Comment by markotoplak** [comment]
I also saw this one a few times. I do not think it has been fixed yet.
