### ISSUE TITLE
SinkChannelError when inserting Corpus on a Data connection

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-canvas-core#241]
I apologize for the insufficient error description, but the workflow I am working on is big and full of bugs, so I am not entirely sure what causes this issue.

The set up is:
SVM (with a trained model), connected to Predictions, which is failing due to Corpus/Table incompatibility.
Then I try to insert a Corpus widget between SVM and Predictions (onto the Data channel) and I get the below error.

```
------------------------- SinkChannelError Exception --------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/document/commands.py", line 130, in redo
    self.scheme.add_link(self.link)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/scheme.py", line 338, in add_link
    self.insert_link(len(self.__links), link)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/scheme.py", line 295, in insert_link
    self.check_connect(link)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/scheme.py", line 460, in check_connect
    raise SinkChannelError(
orangecanvas.scheme.errors.SinkChannelError: 'Data' is already connected.
-------------------------------------------------------------------------------
```

**Comment by ales-erjavec** [comment]
I cannot duplicate this. It might be a consequence of a previous error that left the workflow model in in inconsistent state.
