### ISSUE TITLE
Error when reloading a moved workflow

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-canvas-core#92]
Ctrl+R reloads the most recent workflow. If the workflow was moved to a different location in the meantime, the user gets an error:

```
----------------------------- EOFError Exception ------------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/application/canvasmain.py", line 1351, in reload_last
    self.open_scheme_file(path)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/application/canvasmain.py", line 1077, in open_scheme_file
    self.ask_load_swp_if_exists()
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/application/canvasmain.py", line 1634, in ask_load_swp_if_exists
    self.ask_load_swp()
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/application/canvasmain.py", line 1653, in ask_load_swp
    self.load_swp()
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/application/canvasmain.py", line 1683, in load_swp
    self.load_swp_from(swpnames[0])
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/application/canvasmain.py", line 1703, in load_swp_from
    loaded = Unpickler(f, document.scheme()).load()
EOFError: Ran out of input
-------------------------------------------------------------------------------
```

We should handle this gracefully - with a warning _Workflow not found_ or similar.

**Comment by ales-erjavec** [comment]
Fixed by gh-93
